# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x04user\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"=\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"]\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"!\n\x10ListUsersRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\">\n\x13\x42\x61tchCreateResponse\x12\x15\n\rusers_created\x18\x01 \x01(\x05\x12\x10\n\x08user_ids\x18\x02 \x03(\x05\"B\n\x0bUserMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2\xc5\x02\n\x0bUserService\x12\x35\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\"\x00\x12;\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\"\x00\x12;\n\tListUsers\x12\x16.user.ListUsersRequest\x1a\x12.user.UserResponse\"\x00\x30\x01\x12J\n\x10\x42\x61tchCreateUsers\x12\x17.user.CreateUserRequest\x1a\x19.user.BatchCreateResponse\"\x00(\x01\x12\x39\n\x0bStreamUsers\x12\x11.user.UserMessage\x1a\x11.user.UserMessage\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=28
  _globals['_GETUSERREQUEST']._serialized_end=61
  _globals['_CREATEUSERREQUEST']._serialized_start=63
  _globals['_CREATEUSERREQUEST']._serialized_end=124
  _globals['_USERRESPONSE']._serialized_start=126
  _globals['_USERRESPONSE']._serialized_end=219
  _globals['_LISTUSERSREQUEST']._serialized_start=221
  _globals['_LISTUSERSREQUEST']._serialized_end=254
  _globals['_BATCHCREATERESPONSE']._serialized_start=256
  _globals['_BATCHCREATERESPONSE']._serialized_end=318
  _globals['_USERMESSAGE']._serialized_start=320
  _globals['_USERMESSAGE']._serialized_end=386
  _globals['_USERSERVICE']._serialized_start=389
  _globals['_USERSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
