FROM python:3.11-slim

WORKDIR /app

# Copy gRPC files
COPY ../grpc-demo/*.py /app/
COPY ../grpc-demo/requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 50051

CMD ["python", "server.py"]
